// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umlsdpvbxcvidplksdvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtbHNkcHZieGN2aWRwbGtzZHZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NDI2MjAsImV4cCI6MjA2ODExODYyMH0.ICG2ea6Vxwq6QB8h7_QLYj0pUH-xvdo5O6fts8dtpkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});